// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_data
DataFrame get_data(std::string& dataset_id);
RcppExport SEXP _rgrpc_get_data(SEXP dataset_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string& >::type dataset_id(dataset_idSEXP);
    rcpp_result_gen = Rcpp::wrap(get_data(dataset_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgrpc_get_data", (DL_FUNC) &_rgrpc_get_data, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgrpc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
